import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";

/** shadcn */
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const fontMontserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased font-montserrat",
          fontMontserrat.variable
        )}
      >
        {children}
      </body>
    </html>
  );
}
