import type { Metadata } from "next";
import { Inter, Montserrat, Kumbh_Sans } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import Providers from "@/lib/providers/query-provider";

/** shadcn */
import { cn } from "@/lib/utils";

const inter = Inter({ subsets: ["latin"] });
const fontMontserrat = Montserrat({
  subsets: ["cyrillic"],
  variable: "--font-montserrat",
});
const fontKumbhSans = Kumbh_Sans({
  subsets: ["latin"],
  variable: "--font-kumbh-sans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-background antialiased font-kumbhSans",
          fontKumbhSans.variable,
          fontMontserrat.variable
        )}
      >
        <main>
          <Providers>{children}</Providers>
        </main>
        <Toaster />
      </body>
    </html>
  );
}
